"""autogenerated by genpy from roomba_500_series/Buttons.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Buttons(genpy.Message):
  _md5sum = "2c6635fea08c0a11307b4518b1f7fd79"
  _type = "roomba_500_series/Buttons"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
bool clean
bool spot
bool dock
bool day
bool hour
bool minute
bool schedule
bool clock

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','clean','spot','dock','day','hour','minute','schedule','clock']
  _slot_types = ['std_msgs/Header','bool','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,clean,spot,dock,day,hour,minute,schedule,clock

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Buttons, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.clean is None:
        self.clean = False
      if self.spot is None:
        self.spot = False
      if self.dock is None:
        self.dock = False
      if self.day is None:
        self.day = False
      if self.hour is None:
        self.hour = False
      if self.minute is None:
        self.minute = False
      if self.schedule is None:
        self.schedule = False
      if self.clock is None:
        self.clock = False
    else:
      self.header = std_msgs.msg.Header()
      self.clean = False
      self.spot = False
      self.dock = False
      self.day = False
      self.hour = False
      self.minute = False
      self.schedule = False
      self.clock = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_8B.pack(_x.clean, _x.spot, _x.dock, _x.day, _x.hour, _x.minute, _x.schedule, _x.clock))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.clean, _x.spot, _x.dock, _x.day, _x.hour, _x.minute, _x.schedule, _x.clock,) = _struct_8B.unpack(str[start:end])
      self.clean = bool(self.clean)
      self.spot = bool(self.spot)
      self.dock = bool(self.dock)
      self.day = bool(self.day)
      self.hour = bool(self.hour)
      self.minute = bool(self.minute)
      self.schedule = bool(self.schedule)
      self.clock = bool(self.clock)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_8B.pack(_x.clean, _x.spot, _x.dock, _x.day, _x.hour, _x.minute, _x.schedule, _x.clock))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.clean, _x.spot, _x.dock, _x.day, _x.hour, _x.minute, _x.schedule, _x.clock,) = _struct_8B.unpack(str[start:end])
      self.clean = bool(self.clean)
      self.spot = bool(self.spot)
      self.dock = bool(self.dock)
      self.day = bool(self.day)
      self.hour = bool(self.hour)
      self.minute = bool(self.minute)
      self.schedule = bool(self.schedule)
      self.clock = bool(self.clock)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_8B = struct.Struct("<8B")
_struct_3I = struct.Struct("<3I")
