"""autogenerated by genpy from roomba_500_series/Leds.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Leds(genpy.Message):
  _md5sum = "d69ee7dfd55b5e80fe8d68fdc28e3612"
  _type = "roomba_500_series/Leds"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
bool warning
bool dock
bool spot
bool dirt_detect
uint8 clean_color
uint8 clean_intensity

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','warning','dock','spot','dirt_detect','clean_color','clean_intensity']
  _slot_types = ['std_msgs/Header','bool','bool','bool','bool','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,warning,dock,spot,dirt_detect,clean_color,clean_intensity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Leds, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.warning is None:
        self.warning = False
      if self.dock is None:
        self.dock = False
      if self.spot is None:
        self.spot = False
      if self.dirt_detect is None:
        self.dirt_detect = False
      if self.clean_color is None:
        self.clean_color = 0
      if self.clean_intensity is None:
        self.clean_intensity = 0
    else:
      self.header = std_msgs.msg.Header()
      self.warning = False
      self.dock = False
      self.spot = False
      self.dirt_detect = False
      self.clean_color = 0
      self.clean_intensity = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6B.pack(_x.warning, _x.dock, _x.spot, _x.dirt_detect, _x.clean_color, _x.clean_intensity))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.warning, _x.dock, _x.spot, _x.dirt_detect, _x.clean_color, _x.clean_intensity,) = _struct_6B.unpack(str[start:end])
      self.warning = bool(self.warning)
      self.dock = bool(self.dock)
      self.spot = bool(self.spot)
      self.dirt_detect = bool(self.dirt_detect)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6B.pack(_x.warning, _x.dock, _x.spot, _x.dirt_detect, _x.clean_color, _x.clean_intensity))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.warning, _x.dock, _x.spot, _x.dirt_detect, _x.clean_color, _x.clean_intensity,) = _struct_6B.unpack(str[start:end])
      self.warning = bool(self.warning)
      self.dock = bool(self.dock)
      self.spot = bool(self.spot)
      self.dirt_detect = bool(self.dirt_detect)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_6B = struct.Struct("<6B")
