/* Auto-generated by genmsg_cpp for file /home/igor/rosbuild_ws/roomba_robot/roomba_500_series/msg/Brushes.msg */
#ifndef ROOMBA_500_SERIES_MESSAGE_BRUSHES_H
#define ROOMBA_500_SERIES_MESSAGE_BRUSHES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace roomba_500_series
{
template <class ContainerAllocator>
struct Brushes_ {
  typedef Brushes_<ContainerAllocator> Type;

  Brushes_()
  : header()
  , main_brush(false)
  , main_brush_pwm(0)
  , main_brush_direction(false)
  , side_brush(false)
  , side_brush_pwm(0)
  , side_brush_clockwise(false)
  , vacuum(false)
  , vacuum_pwm(0)
  {
  }

  Brushes_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , main_brush(false)
  , main_brush_pwm(0)
  , main_brush_direction(false)
  , side_brush(false)
  , side_brush_pwm(0)
  , side_brush_clockwise(false)
  , vacuum(false)
  , vacuum_pwm(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _main_brush_type;
  uint8_t main_brush;

  typedef int8_t _main_brush_pwm_type;
  int8_t main_brush_pwm;

  typedef uint8_t _main_brush_direction_type;
  uint8_t main_brush_direction;

  typedef uint8_t _side_brush_type;
  uint8_t side_brush;

  typedef int8_t _side_brush_pwm_type;
  int8_t side_brush_pwm;

  typedef uint8_t _side_brush_clockwise_type;
  uint8_t side_brush_clockwise;

  typedef uint8_t _vacuum_type;
  uint8_t vacuum;

  typedef int8_t _vacuum_pwm_type;
  int8_t vacuum_pwm;


  typedef boost::shared_ptr< ::roomba_500_series::Brushes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roomba_500_series::Brushes_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Brushes
typedef  ::roomba_500_series::Brushes_<std::allocator<void> > Brushes;

typedef boost::shared_ptr< ::roomba_500_series::Brushes> BrushesPtr;
typedef boost::shared_ptr< ::roomba_500_series::Brushes const> BrushesConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::roomba_500_series::Brushes_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::roomba_500_series::Brushes_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace roomba_500_series

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::roomba_500_series::Brushes_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::roomba_500_series::Brushes_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::roomba_500_series::Brushes_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d4c497f02ce3244991df05e0d729013c";
  }

  static const char* value(const  ::roomba_500_series::Brushes_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd4c497f02ce32449ULL;
  static const uint64_t static_value2 = 0x91df05e0d729013cULL;
};

template<class ContainerAllocator>
struct DataType< ::roomba_500_series::Brushes_<ContainerAllocator> > {
  static const char* value() 
  {
    return "roomba_500_series/Brushes";
  }

  static const char* value(const  ::roomba_500_series::Brushes_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::roomba_500_series::Brushes_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool main_brush\n\
int8 main_brush_pwm\n\
bool main_brush_direction\n\
bool side_brush\n\
int8 side_brush_pwm\n\
bool side_brush_clockwise\n\
bool vacuum\n\
int8 vacuum_pwm\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::roomba_500_series::Brushes_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::roomba_500_series::Brushes_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::roomba_500_series::Brushes_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::roomba_500_series::Brushes_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.main_brush);
    stream.next(m.main_brush_pwm);
    stream.next(m.main_brush_direction);
    stream.next(m.side_brush);
    stream.next(m.side_brush_pwm);
    stream.next(m.side_brush_clockwise);
    stream.next(m.vacuum);
    stream.next(m.vacuum_pwm);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Brushes_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roomba_500_series::Brushes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::roomba_500_series::Brushes_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "main_brush: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.main_brush);
    s << indent << "main_brush_pwm: ";
    Printer<int8_t>::stream(s, indent + "  ", v.main_brush_pwm);
    s << indent << "main_brush_direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.main_brush_direction);
    s << indent << "side_brush: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.side_brush);
    s << indent << "side_brush_pwm: ";
    Printer<int8_t>::stream(s, indent + "  ", v.side_brush_pwm);
    s << indent << "side_brush_clockwise: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.side_brush_clockwise);
    s << indent << "vacuum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vacuum);
    s << indent << "vacuum_pwm: ";
    Printer<int8_t>::stream(s, indent + "  ", v.vacuum_pwm);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROOMBA_500_SERIES_MESSAGE_BRUSHES_H

