/* Auto-generated by genmsg_cpp for file /home/igor/rosbuild_ws/roomba_robot/roomba_500_series/msg/GoDockGoal.msg */
#ifndef ROOMBA_500_SERIES_MESSAGE_GODOCKGOAL_H
#define ROOMBA_500_SERIES_MESSAGE_GODOCKGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace roomba_500_series
{
template <class ContainerAllocator>
struct GoDockGoal_ {
  typedef GoDockGoal_<ContainerAllocator> Type;

  GoDockGoal_()
  : timeout()
  {
  }

  GoDockGoal_(const ContainerAllocator& _alloc)
  : timeout()
  {
  }

  typedef ros::Duration _timeout_type;
  ros::Duration timeout;


  typedef boost::shared_ptr< ::roomba_500_series::GoDockGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roomba_500_series::GoDockGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GoDockGoal
typedef  ::roomba_500_series::GoDockGoal_<std::allocator<void> > GoDockGoal;

typedef boost::shared_ptr< ::roomba_500_series::GoDockGoal> GoDockGoalPtr;
typedef boost::shared_ptr< ::roomba_500_series::GoDockGoal const> GoDockGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::roomba_500_series::GoDockGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::roomba_500_series::GoDockGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace roomba_500_series

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::roomba_500_series::GoDockGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::roomba_500_series::GoDockGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::roomba_500_series::GoDockGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2980f386b15a95a8b7dc2d158ace81dc";
  }

  static const char* value(const  ::roomba_500_series::GoDockGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2980f386b15a95a8ULL;
  static const uint64_t static_value2 = 0xb7dc2d158ace81dcULL;
};

template<class ContainerAllocator>
struct DataType< ::roomba_500_series::GoDockGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "roomba_500_series/GoDockGoal";
  }

  static const char* value(const  ::roomba_500_series::GoDockGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::roomba_500_series::GoDockGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
duration timeout\n\
\n\
";
  }

  static const char* value(const  ::roomba_500_series::GoDockGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::roomba_500_series::GoDockGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::roomba_500_series::GoDockGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.timeout);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GoDockGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roomba_500_series::GoDockGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::roomba_500_series::GoDockGoal_<ContainerAllocator> & v) 
  {
    s << indent << "timeout: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.timeout);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROOMBA_500_SERIES_MESSAGE_GODOCKGOAL_H

