/* Auto-generated by genmsg_cpp for file /home/igor/rosbuild_ws/roomba_robot/roomba_500_series/msg/GoDockFeedback.msg */
#ifndef ROOMBA_500_SERIES_MESSAGE_GODOCKFEEDBACK_H
#define ROOMBA_500_SERIES_MESSAGE_GODOCKFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace roomba_500_series
{
template <class ContainerAllocator>
struct GoDockFeedback_ {
  typedef GoDockFeedback_<ContainerAllocator> Type;

  GoDockFeedback_()
  : feedback()
  {
  }

  GoDockFeedback_(const ContainerAllocator& _alloc)
  : feedback(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _feedback_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  feedback;


  typedef boost::shared_ptr< ::roomba_500_series::GoDockFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roomba_500_series::GoDockFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GoDockFeedback
typedef  ::roomba_500_series::GoDockFeedback_<std::allocator<void> > GoDockFeedback;

typedef boost::shared_ptr< ::roomba_500_series::GoDockFeedback> GoDockFeedbackPtr;
typedef boost::shared_ptr< ::roomba_500_series::GoDockFeedback const> GoDockFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::roomba_500_series::GoDockFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::roomba_500_series::GoDockFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace roomba_500_series

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::roomba_500_series::GoDockFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::roomba_500_series::GoDockFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::roomba_500_series::GoDockFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c14cdf907e5c7c7fd47292add15660f0";
  }

  static const char* value(const  ::roomba_500_series::GoDockFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc14cdf907e5c7c7fULL;
  static const uint64_t static_value2 = 0xd47292add15660f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::roomba_500_series::GoDockFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "roomba_500_series/GoDockFeedback";
  }

  static const char* value(const  ::roomba_500_series::GoDockFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::roomba_500_series::GoDockFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
string feedback\n\
\n\
\n\
";
  }

  static const char* value(const  ::roomba_500_series::GoDockFeedback_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::roomba_500_series::GoDockFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.feedback);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GoDockFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roomba_500_series::GoDockFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::roomba_500_series::GoDockFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "feedback: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.feedback);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROOMBA_500_SERIES_MESSAGE_GODOCKFEEDBACK_H

