/* Auto-generated by genmsg_cpp for file /home/igor/rosbuild_ws/roomba_robot/roomba_500_series/msg/GoDockResult.msg */
#ifndef ROOMBA_500_SERIES_MESSAGE_GODOCKRESULT_H
#define ROOMBA_500_SERIES_MESSAGE_GODOCKRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace roomba_500_series
{
template <class ContainerAllocator>
struct GoDockResult_ {
  typedef GoDockResult_<ContainerAllocator> Type;

  GoDockResult_()
  : dock(false)
  {
  }

  GoDockResult_(const ContainerAllocator& _alloc)
  : dock(false)
  {
  }

  typedef uint8_t _dock_type;
  uint8_t dock;


  typedef boost::shared_ptr< ::roomba_500_series::GoDockResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roomba_500_series::GoDockResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GoDockResult
typedef  ::roomba_500_series::GoDockResult_<std::allocator<void> > GoDockResult;

typedef boost::shared_ptr< ::roomba_500_series::GoDockResult> GoDockResultPtr;
typedef boost::shared_ptr< ::roomba_500_series::GoDockResult const> GoDockResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::roomba_500_series::GoDockResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::roomba_500_series::GoDockResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace roomba_500_series

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::roomba_500_series::GoDockResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::roomba_500_series::GoDockResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::roomba_500_series::GoDockResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "035360b0bb03f7f742a0b2d734a3a660";
  }

  static const char* value(const  ::roomba_500_series::GoDockResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x035360b0bb03f7f7ULL;
  static const uint64_t static_value2 = 0x42a0b2d734a3a660ULL;
};

template<class ContainerAllocator>
struct DataType< ::roomba_500_series::GoDockResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "roomba_500_series/GoDockResult";
  }

  static const char* value(const  ::roomba_500_series::GoDockResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::roomba_500_series::GoDockResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
bool dock\n\
\n\
";
  }

  static const char* value(const  ::roomba_500_series::GoDockResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::roomba_500_series::GoDockResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::roomba_500_series::GoDockResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.dock);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GoDockResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roomba_500_series::GoDockResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::roomba_500_series::GoDockResult_<ContainerAllocator> & v) 
  {
    s << indent << "dock: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dock);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROOMBA_500_SERIES_MESSAGE_GODOCKRESULT_H

