/* Auto-generated by genmsg_cpp for file /home/igor/rosbuild_ws/roomba_robot/roomba_500_series/msg/Leds.msg */
#ifndef ROOMBA_500_SERIES_MESSAGE_LEDS_H
#define ROOMBA_500_SERIES_MESSAGE_LEDS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace roomba_500_series
{
template <class ContainerAllocator>
struct Leds_ {
  typedef Leds_<ContainerAllocator> Type;

  Leds_()
  : header()
  , warning(false)
  , dock(false)
  , spot(false)
  , dirt_detect(false)
  , clean_color(0)
  , clean_intensity(0)
  {
  }

  Leds_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , warning(false)
  , dock(false)
  , spot(false)
  , dirt_detect(false)
  , clean_color(0)
  , clean_intensity(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _warning_type;
  uint8_t warning;

  typedef uint8_t _dock_type;
  uint8_t dock;

  typedef uint8_t _spot_type;
  uint8_t spot;

  typedef uint8_t _dirt_detect_type;
  uint8_t dirt_detect;

  typedef uint8_t _clean_color_type;
  uint8_t clean_color;

  typedef uint8_t _clean_intensity_type;
  uint8_t clean_intensity;


  typedef boost::shared_ptr< ::roomba_500_series::Leds_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roomba_500_series::Leds_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Leds
typedef  ::roomba_500_series::Leds_<std::allocator<void> > Leds;

typedef boost::shared_ptr< ::roomba_500_series::Leds> LedsPtr;
typedef boost::shared_ptr< ::roomba_500_series::Leds const> LedsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::roomba_500_series::Leds_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::roomba_500_series::Leds_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace roomba_500_series

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::roomba_500_series::Leds_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::roomba_500_series::Leds_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::roomba_500_series::Leds_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d69ee7dfd55b5e80fe8d68fdc28e3612";
  }

  static const char* value(const  ::roomba_500_series::Leds_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd69ee7dfd55b5e80ULL;
  static const uint64_t static_value2 = 0xfe8d68fdc28e3612ULL;
};

template<class ContainerAllocator>
struct DataType< ::roomba_500_series::Leds_<ContainerAllocator> > {
  static const char* value() 
  {
    return "roomba_500_series/Leds";
  }

  static const char* value(const  ::roomba_500_series::Leds_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::roomba_500_series::Leds_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool warning\n\
bool dock\n\
bool spot\n\
bool dirt_detect\n\
uint8 clean_color\n\
uint8 clean_intensity\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::roomba_500_series::Leds_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::roomba_500_series::Leds_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::roomba_500_series::Leds_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::roomba_500_series::Leds_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.warning);
    stream.next(m.dock);
    stream.next(m.spot);
    stream.next(m.dirt_detect);
    stream.next(m.clean_color);
    stream.next(m.clean_intensity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Leds_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roomba_500_series::Leds_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::roomba_500_series::Leds_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "warning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.warning);
    s << indent << "dock: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dock);
    s << indent << "spot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.spot);
    s << indent << "dirt_detect: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dirt_detect);
    s << indent << "clean_color: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clean_color);
    s << indent << "clean_intensity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clean_intensity);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROOMBA_500_SERIES_MESSAGE_LEDS_H

