/* Auto-generated by genmsg_cpp for file /home/igor/rosbuild_ws/roomba_robot/roomba_500_series/msg/PlaySong.msg */
#ifndef ROOMBA_500_SERIES_MESSAGE_PLAYSONG_H
#define ROOMBA_500_SERIES_MESSAGE_PLAYSONG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace roomba_500_series
{
template <class ContainerAllocator>
struct PlaySong_ {
  typedef PlaySong_<ContainerAllocator> Type;

  PlaySong_()
  : header()
  , song_number(0)
  {
  }

  PlaySong_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , song_number(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _song_number_type;
  uint8_t song_number;


  typedef boost::shared_ptr< ::roomba_500_series::PlaySong_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roomba_500_series::PlaySong_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PlaySong
typedef  ::roomba_500_series::PlaySong_<std::allocator<void> > PlaySong;

typedef boost::shared_ptr< ::roomba_500_series::PlaySong> PlaySongPtr;
typedef boost::shared_ptr< ::roomba_500_series::PlaySong const> PlaySongConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::roomba_500_series::PlaySong_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::roomba_500_series::PlaySong_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace roomba_500_series

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::roomba_500_series::PlaySong_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::roomba_500_series::PlaySong_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::roomba_500_series::PlaySong_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4da85658329795298b78d2ec93fdcedc";
  }

  static const char* value(const  ::roomba_500_series::PlaySong_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4da8565832979529ULL;
  static const uint64_t static_value2 = 0x8b78d2ec93fdcedcULL;
};

template<class ContainerAllocator>
struct DataType< ::roomba_500_series::PlaySong_<ContainerAllocator> > {
  static const char* value() 
  {
    return "roomba_500_series/PlaySong";
  }

  static const char* value(const  ::roomba_500_series::PlaySong_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::roomba_500_series::PlaySong_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint8 song_number\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::roomba_500_series::PlaySong_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::roomba_500_series::PlaySong_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::roomba_500_series::PlaySong_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::roomba_500_series::PlaySong_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.song_number);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PlaySong_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roomba_500_series::PlaySong_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::roomba_500_series::PlaySong_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "song_number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.song_number);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROOMBA_500_SERIES_MESSAGE_PLAYSONG_H

