/* Auto-generated by genmsg_cpp for file /home/igor/rosbuild_ws/roomba_robot/roomba_500_series/msg/RoombaIR.msg */
#ifndef ROOMBA_500_SERIES_MESSAGE_ROOMBAIR_H
#define ROOMBA_500_SERIES_MESSAGE_ROOMBAIR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace roomba_500_series
{
template <class ContainerAllocator>
struct RoombaIR_ {
  typedef RoombaIR_<ContainerAllocator> Type;

  RoombaIR_()
  : header()
  , state(false)
  , signal(0)
  {
  }

  RoombaIR_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , state(false)
  , signal(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _state_type;
  uint8_t state;

  typedef uint16_t _signal_type;
  uint16_t signal;


  typedef boost::shared_ptr< ::roomba_500_series::RoombaIR_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roomba_500_series::RoombaIR_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RoombaIR
typedef  ::roomba_500_series::RoombaIR_<std::allocator<void> > RoombaIR;

typedef boost::shared_ptr< ::roomba_500_series::RoombaIR> RoombaIRPtr;
typedef boost::shared_ptr< ::roomba_500_series::RoombaIR const> RoombaIRConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::roomba_500_series::RoombaIR_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::roomba_500_series::RoombaIR_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace roomba_500_series

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::roomba_500_series::RoombaIR_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::roomba_500_series::RoombaIR_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::roomba_500_series::RoombaIR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a2eb843f93c486d3df9c635f426907b6";
  }

  static const char* value(const  ::roomba_500_series::RoombaIR_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa2eb843f93c486d3ULL;
  static const uint64_t static_value2 = 0xdf9c635f426907b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::roomba_500_series::RoombaIR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "roomba_500_series/RoombaIR";
  }

  static const char* value(const  ::roomba_500_series::RoombaIR_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::roomba_500_series::RoombaIR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool state\n\
uint16 signal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::roomba_500_series::RoombaIR_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::roomba_500_series::RoombaIR_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::roomba_500_series::RoombaIR_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::roomba_500_series::RoombaIR_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.state);
    stream.next(m.signal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RoombaIR_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roomba_500_series::RoombaIR_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::roomba_500_series::RoombaIR_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "signal: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.signal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROOMBA_500_SERIES_MESSAGE_ROOMBAIR_H

